apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    app: my-app
  namespace: default
spec:
  type: NodePort
  ports:
   - port: 31026
     targetPort: 5000
  selector:
    app: my-app
